//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoNotHarm
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DoNotHarmEntities : DbContext
    {
        public DoNotHarmEntities()
            : base("name=DoNotHarmEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Countri> Countris { get; set; }
        public virtual DbSet<Insurance> Insurances { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<SocialType> SocialTypes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UsersService> UsersServices { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
        public virtual DbSet<EnterStatus> EnterStatuses { get; set; }
        public virtual DbSet<HistoryLogin> HistoryLogins { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderService> OrderServices { get; set; }
        public virtual DbSet<OrderUser> OrderUsers { get; set; }
    }
}
